[package]
name = "article-render-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true

fred.workspace = true
sqlx.workspace = true

reqwest.workspace = true
comrak.workspace = true

thiserror.workspace = true
anyhow.workspace = true
clap.workspace = true

shared.workspace = true
redis.workspace = true
url.workspace = true
